spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/todo
    username: postgres
    password: Alialiali1573
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
logging:
  level: 
    root: INFO